apiVersion: v1
kind: Service
metadata:
  name: web-loadbalancer
spec:
  selector:
    component: web
  ports:
    - port: 5050
      targetPort: 5050
      name: http-port
    - port: 5051
      targetPort: 5051
      name: https-port
  type: LoadBalancer
  
