apiVersion: v1
kind: Service
metadata:
  name: octopetshop-productservice-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: productservice
  ports:
    - port: 5020
      targetPort: 5020
      name: http-port
    - port: 5020
      targetPort: 5020
      name: https-port
