apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopetshop-staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: octopetshop
spec:
  project: default
  destination:
    name: in-cluster
    namespace: octopetshop-staging
  source:
    path: k8s/staging
    repoURL: https://github.com/adamoctoclosegitops/OctoPetShop-Enterprise.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
