apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopetshop-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    name: in-cluster
    namespace: octopetshop-development
  source:
    path: k8s/dev
    repoURL: https://github.com/adamoctoclosegitops/OctoPetShop-Enterprise.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
