apiVersion: v1
kind: Service
metadata:
  name: web-loadbalancer
spec:
  selector:
    component: web
  ports:
    - port: 5070
      targetPort: 5070
      name: http-port
    - port: 5071
      targetPort: 5071
      name: https-port
  type: LoadBalancer
  
