apiVersion: v1
kind: Service
metadata:
  name: web-loadbalancer
spec:
  selector:
    component: web
  ports:
    - port: 5080
      targetPort: 5080
      name: http-port
    - port: 5081
      targetPort: 5081
      name: https-port
  type: LoadBalancer
  
